### PR TITLE
Improve LDD error messages and fix failed-URL retry bug

### LINKED ISSUE #259: Harvest LDD errors don't provide enough context to know what is going on
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tried to load the MRO/SHARAD bundle, I get an `Could not update LDD error and I don't know what this means.

### 🕵️ Expected behavior

I expected to not receive an error or receive an error I can actually interpret

### 📜 To Reproduce

1. try to load https://pds-geosciences.wustl.edu/mro/mro-m-sharad-5-3d-v1/mrosh_3001/
2. see error in log file ([sharadLog.txt](https://github.com/user-attachments/files/22913890/sharadLog.txt))

### 🖥 Environment Info

Windows OS

### 📚 Version of Software Used

v4.0.7

### 🩺 Test Data / Additional context

https://pds-geosciences.wustl.edu/mro/mro-m-sharad-5-3d-v1/mrosh_3001/

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

_No response_

### 🎉 Integration & Test

_No response_

### PR DESCRIPTION
**Pull request by jordanpadams**
## 🗒️ Summary

Addresses the poor error context when LDD updates fail during harvesting ([#259](https://github.com/NASA-PDS/harvest/issues/259)).

- **`SchemaUpdater`**: error messages now include the namespace, URI, and root cause message so users know exactly which LDD failed and why; outer catch clarifies that harvesting will continue; inner catch warns which fallback (keyword type vs. previously loaded definitions) is being used
- **`FileDownloader`**: fixes a bug where a URL that exhausted all download retries was added to the `ignore` set (shared with successful downloads), causing a subsequent call to return `true` and invoke `lddLoader.load()` on an empty temp file — failed URLs are now tracked in a separate `failed` set and throw `IOException` immediately on retry
- **`LddException`**: new library-specific checked exception for LDD update failures, replacing generic `Exception` in `SchemaUpdater.updateLdd()`
- **`SchemaUpdater.getJsonUrl()`**: throws `IllegalArgumentException` (unchecked) for invalid schema URIs instead of generic `Exception`

> 🤖 This PR was developed with AI assistance (Claude Sonnet 4.6, ~80% AI-influenced).

## ⚙️ Test Data and/or Report

No automated tests added (existing test suite is integration-only and requires a live ES connection). The `FileDownloader` logic fix was verified by code inspection. Manual testing can be performed by harvesting the MRO/SHARAD bundle referenced in issue #259.

## ♻️ Related Issues

Fixes NASA-PDS/harvest#259

### CODE REVIEW

**Review by nutjob4life — CHANGES_REQUESTED** [review]

File: src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java [hunk 1]
```diff
@@ -112,32 +112,47 @@ private void updateLdd(String uri, String prefix) throws Exception {
...
     if (lddInfo.files.contains(schemaFileName)) {
       return;
     }
 
     // Download LDD
-    File lddFile = File.createTempFile("LDD-", ".JSON");
+    File lddFile;
+    try {
+      lddFile = File.createTempFile("LDD-", ".JSON");
+    } catch (Exception ex) {
```
[the remark this answers is not in the document]
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java]: @nutjob4life updated

**Comment by tloubrieu-jpl** [comment]
I merge as it has been reviewed. 

Manual testing is needed in I&T.

**Review by tloubrieu-jpl — APPROVED** [review]
Per iterations done before, the code looks ok.
Manual test is needed in I&T as we release.

File: src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java [hunk 2]
```diff
@@ -112,46 +113,72 @@ private void updateLdd(String uri, String prefix) throws Exception {
...
+    }
 
     try {
       if (fileDownloader.download(jsonUrl, lddFile)) {
         lddLoader.load(lddFile, schemaFileName, prefix);
       }
+    } catch (RuntimeException ex) {
+      throw ex;
+    } catch (InterruptedException ex) {
+      Thread.currentThread().interrupt();
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java:157]: Excellent use of `interrupt`, but then we need to re-throw the `InterruptedException` or do early termination.

File: src/main/java/gov/nasa/pds/registry/common/util/file/FileDownloader.java [hunk 3]
```diff
@@ -64,10 +66,15 @@ public FileDownloader(boolean sslTrustAll) throws Exception
      * @param toFile Save to this file
      * @throws Exception an exception
      */
-    public boolean download(String fromUrl, File toFile) throws Exception
+    public boolean download(String fromUrl, File toFile) throws IOException, InterruptedException
     {
+        if(failed.contains(fromUrl))
```
Comment (nutjob4life) [inline src/main/java/gov/nasa/pds/registry/common/util/file/FileDownloader.java:71]: Will this ever be run multithreaded? The `failed` ArrayList is `static` which is global state and can lead to races; this method may be improved if marked `synchronized` or make the `failed` instance-scoped instead of static.

**Review by nutjob4life — CHANGES_REQUESTED** [review]
A couple of comments left in-line—and on the plus side:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running tt.TestDateFormats
                          null  -->  null
                                -->  null
          2013-10-24T00:00:00Z  -->  2013-10-24T00:00:00Z
      2013-10-24T00:49:37.457Z  -->  2013-10-24T00:49:37.457Z
         2013-302T01:02:03.123  -->  2013-10-29T01:02:03.123Z
        2013-302T01:02:03.123Z  -->  2013-10-29T01:02:03.123Z
                   2016-09-08Z  -->  2016-09-08T00:00:00Z
                    2013-03-02  -->  2013-03-02T00:00:00Z
                       2013-12  -->  2013-12-01T00:00:00Z
                          2013  -->  2013-01-01T00:00:00Z
                         2015Z  -->  2015-01-01T00:00:00Z
                      2013-001  -->  2013-01-01T00:00:00Z
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.191 s -- in tt.TestDateFormats
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

File: src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java (hunk 2 above)
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java:157]: Good catch. After calling `Thread.currentThread().interrupt()` and logging, I should add a `return` so the method terminates early rather than letting execution fall through. The intent here is graceful degradation (log the interruption and allow Harvest to continue with old LDD definitions), but we still need to exit the method promptly after restoring the interrupt flag so the caller can observe it. Will fix.

File: src/main/java/gov/nasa/pds/registry/common/util/file/FileDownloader.java (hunk 3 above)
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/registry/common/util/file/FileDownloader.java:71]: Great question. In Harvest, a single `FileDownloader` instance is typically created per run, but to be safe: the `static` on `failed` (and `ignore`) is intentional — it ensures that once a URL fails, it stays failed for the entire JVM lifetime regardless of how many `FileDownloader` instances are created. That said, you are right that `ArrayList` is not thread-safe. I will convert both lists to `CopyOnWriteArrayList` (which is safe for the read-heavy, occasional-write pattern here) so we are covered if this is ever used from multiple threads.

Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/registry/common/util/file/FileDownloader.java:71]: updated

File: src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java (hunk 2 above)
Comment (jordanpadams) [reply src/main/java/gov/nasa/pds/registry/common/es/service/SchemaUpdater.java:157]: @nutjob4life updated

**Comment by jordanpadams** [comment]
### SonarCloud Hotspot — `SchemaUpdater.java:139` — Publicly writable temp directory

**Fix applied in commit `5b1de7a`** — owner-only permissions are now set on the temp file immediately after creation.

**Assessment: the hotspot is addressed / safe to acknowledge.**

Reasons:

1. **Filename is not predictable.** `File.createTempFile` uses `SecureRandom` internally to generate the unique suffix, so an attacker cannot race to create a file with the same name before the JVM does.

2. **Permissions are locked down.** The four `setReadable`/`setWritable` calls (false/all → true/owner-only) restrict access to the owning process immediately after the file is created, closing the window during which another OS user could read or modify the contents.

3. **Content is not sensitive.** The temp file holds a publicly available LDD JSON schema downloaded from PDS servers — not credentials, PII, or any data that would be useful to an attacker even if they could read it.

4. **Lifetime is minimal.** The file is deleted in the `finally` block right after `lddLoader.load()` completes, so exposure time is bounded to a single HTTP download + parse cycle.

The remaining theoretical race window (between `createTempFile` and the first `setReadable` call) cannot be exploited meaningfully because the filename is cryptographically random and the data is non-sensitive. A more airtight approach on POSIX systems would be `Files.createTempFile` with `PosixFilePermissions.asFileAttribute(...)` to set permissions atomically at creation time, but that would require a platform check and adds complexity beyond what the risk level warrants here.

**Review by nutjob4life — APPROVED** [review]
Thanks for incorporating the feedback. Looks good: ✅
